/* UGPHONE MOD - shared Node backend mode */
const cfg=window, $=id=>document.getElementById(id); let me=null; let poll=null;
const API_BASE=(cfg.UG_API_BASE_URL||'').replace(/\/$/,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display='none',2500)}
function msg(t){if($('authMsg'))$('authMsg').textContent=t}
function token(){return localStorage.getItem('ug_api_token')||''}
async function apiFetch(path,opts={}){const h={'Content-Type':'application/json',...(opts.headers||{})};if(token())h.Authorization='Bearer '+token();const r=await fetch(API_BASE+path,{...opts,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Lỗi máy chủ');return j}
function validName(s){return /^[A-Za-z0-9_.-]{3,12}$/.test(s)}
async function init(){try{await restoreSession();await refreshAll();startPolling()}catch(e){console.warn(e);toast('Không kết nối được máy chủ. Hãy kiểm tra server.js và URL backend.')}}
async function restoreSession(){if(!token()){me=null;return}try{me=(await apiFetch('/api/auth/me')).user}catch{localStorage.removeItem('ug_api_token');me=null}}
async function register(){const username=$('username')?.value.trim(),email=$('email')?.value.trim().toLowerCase(),password=$('password')?.value||'';if(!validName(username))return msg('Tên tài khoản 3-12 ký tự, chỉ dùng chữ, số, _, -, .');if(!/^\S+@\S+\.\S+$/.test(email))return msg('Email không hợp lệ.');if(password.length<6)return msg('Mật khẩu phải có ít nhất 6 ký tự.');try{const j=await apiFetch('/api/auth/register',{method:'POST',body:JSON.stringify({username,email,password})});localStorage.setItem('ug_api_token',j.token);me=j.user;syncAuthNav();renderProfile();msg('Tạo tài khoản thành công. Tài khoản dùng chung trên mọi thiết bị.');toast('Đã tạo tài khoản');await refreshAll()}catch(e){msg(e.message);toast(e.message)}}
async function login(){const email=$('email')?.value.trim().toLowerCase(),password=$('password')?.value||'';if(!/^\S+@\S+\.\S+$/.test(email))return msg('Email không hợp lệ.');if(!password)return msg('Vui lòng nhập mật khẩu.');try{const j=await apiFetch('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('ug_api_token',j.token);me=j.user;syncAuthNav();renderProfile();msg('Đăng nhập thành công.');toast('Đã đăng nhập');await refreshAll()}catch(e){msg(e.message);toast(e.message)}}
async function logout(){try{await apiFetch('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('ug_api_token');me=null;syncAuthNav();renderProfile();toast('Đã đăng xuất')}
function syncAuthNav(){const logged=!!me;$('authNav')?.classList.toggle('hidden',logged);$('accountNav')?.classList.toggle('hidden',!logged);const a=$('accountNav');if(a&&me)a.textContent='👤 '+me.username;document.body.classList.toggle('loggedIn',logged)}
function renderProfile(){const b=$('profileBox');if(!b)return;if(!me){b.innerHTML='<p>Chưa đăng nhập.</p>';return}b.innerHTML=`${me.avatar?`<img class="avatarLarge" src="${esc(me.avatar)}">`:''}<p><b>${esc(me.username)}</b> ${me.role==='admin'?'👑 Admin':''}</p><input id="avatarFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><button class="primary" onclick="saveAvatar()">LƯU AVATAR</button><button onclick="removeAvatar()">XÓA AVATAR</button><hr><h3>🔐 Đổi mật khẩu</h3><input id="newPassword" type="password" minlength="6" placeholder="Mật khẩu mới"><input id="newPassword2" type="password" minlength="6" placeholder="Nhập lại mật khẩu"><button class="primary" onclick="changePassword()">ĐỔI MẬT KHẨU</button>`}
async function changePassword(){if(!me)return toast('Bạn cần đăng nhập.');const p=$('newPassword')?.value||'',p2=$('newPassword2')?.value||'';if(p.length<6)return toast('Mật khẩu tối thiểu 6 ký tự.');if(p!==p2)return toast('Hai mật khẩu không khớp.');try{await apiFetch('/api/auth/password',{method:'POST',body:JSON.stringify({password:p})});$('newPassword').value='';$('newPassword2').value='';toast('Đã đổi mật khẩu')}catch(e){toast(e.message)}}
function readImage(input,max,cb){const f=input?.files?.[0];if(!f)return toast('Chọn ảnh trước.');if(f.size>max)return toast('Ảnh quá lớn.');const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
async function saveAvatar(){if(!me)return toast('Bạn cần đăng nhập.');readImage($('avatarFile'),512*1024,async data=>{try{me=(await apiFetch('/api/profile/avatar',{method:'POST',body:JSON.stringify({avatar:data})})).user;renderProfile();loadPublicUsers();toast('Đã đổi avatar')}catch(e){toast(e.message)}})}
async function removeAvatar(){if(!me)return;try{me=(await apiFetch('/api/profile/avatar',{method:'POST',body:JSON.stringify({avatar:''})})).user;renderProfile();loadPublicUsers()}catch(e){toast(e.message)}}
async function loadPublicUsers(){const el=$('publicUsers');if(!el)return;try{const list=(await apiFetch('/api/public/users')).users;if(!list.length){el.innerHTML='<p class="muted">Chưa có tài khoản nào.</p>';return}el.innerHTML=list.map(u=>`<button class="memberCard ${u.role==='admin'?'memberAdmin':''}" onclick="openPublicProfile('${esc(u.id)}')">${u.avatar?`<img class="memberAvatar" src="${esc(u.avatar)}">`:`<div class="memberAvatar memberInitial">${u.role==='admin'?'👑':'U'}</div>`}<span class="memberInfo"><b>${esc(u.username)}</b><small>${u.role==='admin'?'👑 ADMIN':'Thành viên'} • ${u.banned?'ĐÃ BAN':'ĐANG HOẠT ĐỘNG'}</small></span></button>`).join('')}catch(e){el.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function openPublicProfile(id){try{const u=(await apiFetch('/api/public/users')).users.find(x=>x.id===id);if(!u)return toast('Không tìm thấy thành viên.');$('profileModal').classList.remove('hidden');$('profileModalBody').innerHTML=`<div class="profileModalCard">${u.avatar?`<img class="avatarLarge" src="${esc(u.avatar)}">`:`<div class="avatarLarge memberInitial largeInitial">${u.role==='admin'?'👑':'U'}</div>`}<h3>${esc(u.username)}</h3><div class="roleBadge">${u.role==='admin'?'👑 ADMIN':esc(u.role||'user')}</div><p class="muted">Tham gia: ${u.created_at?new Date(u.created_at).toLocaleDateString('vi-VN'):'—'}</p><p>${u.banned?'🔴 ĐÃ BAN':'🟢 ĐANG HOẠT ĐỘNG'}</p></div>`}catch(e){toast(e.message)}}
function closeProfile(){$('profileModal')?.classList.add('hidden')}
async function refreshStats(){try{const s=await apiFetch('/api/stats');if($('onlineCount'))$('onlineCount').textContent=s.online;if($('stats'))$('stats').textContent=`Tài khoản: ${s.users} • KEY đang bật: ${s.keys}`;if($('statUsers'))$('statUsers').textContent=s.users;if($('statBanned'))$('statBanned').textContent=s.banned;if($('statKeys'))$('statKeys').textContent=s.keys;if($('statOnline'))$('statOnline').textContent=s.online}catch{}}
async function claimKey(){if(!me)return toast('Bạn cần đăng nhập.');try{const j=await apiFetch('/api/claim-key',{method:'POST'});$('keyBox').textContent=j.key;$('keyBox').classList.remove('hidden');navigator.clipboard?.writeText(j.key).catch(()=>{});toast('Đã nhận KEY hôm nay')}catch(e){toast(e.message)}}
function postCardHtml(p){const media=p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.title)}" loading="lazy">`:`<div class="postNoImage">🎮<div style="font-size:12px;margin-top:8px">CHƯA CÓ ẢNH</div></div>`;return `<article class="postCard"><div class="postMedia">${media}${p.hot?'<span class="postHot">HOT</span>':''}</div><div class="postBody"><div class="postTitle">${esc(p.title)}</div><div class="postMeta">admin</div><div class="postTags">${p.tag?`<span class="postTag">${esc(p.tag)}</span>`:''}</div><div class="postActions"><button class="claim" onclick="openPostLink('${esc(p.link||'')}')">${esc(p.button_text||'👑 LẤY FREE')}</button></div></div></article>`}
async function renderPosts(){try{const list=(await apiFetch('/api/posts')).posts;const grid=$('postGrid');if(grid)grid.innerHTML=list.length?list.map(postCardHtml).join(''):'<div class="muted" style="grid-column:1/-1;text-align:center;padding:30px">Chưa có bài đăng.</div>';if(me?.role==='admin')renderAdminPosts(list)}catch{}}
function openPostLink(url){if(!url)return toast('Bài này chưa có link.');window.open(url,'_blank','noopener,noreferrer')}
async function publishPost(){if(me?.role!=='admin')return toast('Chỉ Admin mới được đăng bài.');const title=$('postTitle')?.value.trim(),tag=$('postTag')?.value.trim(),link=$('postLink')?.value.trim(),button_text=$('postButton')?.value.trim()||'👑 LẤY FREE (9999)',hot=!!$('postHot')?.checked;if(!title)return toast('Nhập tiêu đề.');if(link&&!/^https?:\/\//i.test(link))return toast('Link không hợp lệ.');const send=async image_url=>{try{await apiFetch('/api/admin/posts',{method:'POST',body:JSON.stringify({title,tag,link,button_text,hot,image_url})});['postTitle','postTag','postLink','postButton'].forEach(id=>$(id)&&($(id).value=''));$('postButton').value='👑 LẤY FREE (9999)';$('postImage').value='';$('postHot').checked=false;await renderPosts();toast('Đã đăng bài')}catch(e){toast(e.message)}};const f=$('postImage')?.files?.[0];if(f){if(f.size>700*1024)return toast('Ảnh quá lớn.');readImage($('postImage'),700*1024,send)}else send('')}
function renderAdminPosts(list){const el=$('adminPostList');if(!el)return;el.innerHTML=list.map(p=>`<div class="postAdminItem"><div><b>${esc(p.title)}</b><br><small>${esc(p.tag||'')} ${p.hot?'• HOT':''}</small></div><div class="adminBtns"><button onclick="togglePost('${esc(p.id)}',false)">ẨN</button></div></div>`).join('')}
async function togglePost(id,active){try{await apiFetch('/api/admin/posts/'+id+'/toggle',{method:'POST',body:JSON.stringify({active})});renderPosts();toast(active?'Đã hiện bài':'Đã ẩn bài')}catch(e){toast(e.message)}}
async function loadChat(){const box=$('chatMessages');if(!box||!me)return;try{const list=(await apiFetch('/api/chat')).messages;box.innerHTML=list.map(m=>`<div class="chatMsg"><b>${esc(m.username)}</b>: ${esc(m.message)}${m.image_url?`<br><img src="${esc(m.image_url)}" style="max-width:240px;border-radius:10px">`:''}</div>`).join('');box.scrollTop=box.scrollHeight}catch(e){toast(e.message)}}
async function sendChat(){if(!me)return toast('Đăng nhập để chat.');const input=$('chatInput'),message=(input?.value||'').trim();if(!message)return;try{await apiFetch('/api/chat',{method:'POST',body:JSON.stringify({message})});input.value='';loadChat()}catch(e){toast(e.message)}}
async function sendChatImage(){if(!me)return toast('Đăng nhập để gửi ảnh.');readImage($('chatImage'),1024*1024,async image_url=>{try{await apiFetch('/api/chat',{method:'POST',body:JSON.stringify({image_url,message:''})});$('chatImage').value='';loadChat()}catch(e){toast(e.message)}})}
async function adminLogin(){const email=$('adminEmail')?.value.trim().toLowerCase(),password=$('adminPass')?.value||'';if(!email||!password)return toast('Nhập email và mật khẩu Admin.');try{const j=await apiFetch('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});if(j.user.role!=='admin'){localStorage.removeItem('ug_api_token');return toast('Tài khoản này không có quyền Admin.')}localStorage.setItem('ug_api_token',j.token);me=j.user;syncAuthNav();renderProfile();toast('Đăng nhập Admin thành công');loadAdmin()}catch(e){toast(e.message)}}
async function adminLogout(){logout();}
async function loadAdmin(){if(!me||me.role!=='admin'){if($('adminPanel'))$('adminPanel').classList.add('hidden');return}$('adminLogin')?.classList.add('hidden');$('adminPanel')?.classList.remove('hidden');await refreshStats();await renderPosts();await renderUsers();await renderAdminChat();await renderKeys();await renderServerState()}
async function renderUsers(){if(me?.role!=='admin')return;try{const list=(await apiFetch('/api/admin/users')).users;const el=$('users');el.innerHTML=list.map(u=>`<div class="user ${u.banned?'ban':''}"><span><b>${esc(u.username)}</b> — <span class="roleBadge">${esc(u.role)}</span> — ${u.banned?'BAN':'OK'}</span><div class="adminBtns"><button onclick="banUser('${esc(u.id)}',${!u.banned})">${u.banned?'GỠ BAN':'BAN'}</button></div></div>`).join('')}catch(e){toast(e.message)}}
async function banUser(id,banned){try{await apiFetch('/api/admin/users/'+id+'/ban',{method:'POST',body:JSON.stringify({banned})});toast(banned?'Đã BAN':'Đã GỠ BAN');renderUsers();loadPublicUsers()}catch(e){toast(e.message)}}
async function setUserRole(id){const role=$('roleSelect')?.value;if(!role)return;try{await apiFetch('/api/admin/users/'+id+'/role',{method:'POST',body:JSON.stringify({role})});toast('Đã cấp role '+role);closeProfile();renderUsers()}catch(e){toast(e.message)}}
async function banIpForUser(id){try{const u=(await apiFetch('/api/admin/users')).users.find(x=>x.id===id);if(!u)return;toast('Chức năng BAN IP dùng endpoint quản trị server.');await apiFetch('/api/admin/ban-ip',{method:'POST',body:JSON.stringify({ip:u.last_ip||''})})}catch(e){toast(e.message)}}
async function addKey(){const key=$('newKey')?.value.trim(),date=$('keyDate')?.value,limit=Number($('keyLimit')?.value||1);if(!key||!date)return toast('Nhập KEY và ngày.');try{await apiFetch('/api/admin/keys',{method:'POST',body:JSON.stringify({key,date,limit})});$('newKey').value='';renderKeys();refreshStats();toast('Đã thêm KEY')}catch(e){toast(e.message)}}
async function renderKeys(){if(me?.role!=='admin')return;try{const list=(await apiFetch('/api/keys')).keys;const el=$('keyList');el.innerHTML=list.map(k=>`<div class="keyitem"><span>${esc(k.date)} — <b>${esc(k.key)}</b> — ${k.used}/${k.limit} — ${k.active?'BẬT':'TẮT'}</span><button onclick="toggleKey('${esc(k.id)}')">${k.active?'TẮT':'BẬT'}</button></div>`).join('')}catch(e){toast(e.message)}}
async function toggleKey(id){try{await apiFetch('/api/admin/keys/'+id+'/toggle',{method:'POST'});renderKeys();refreshStats()}catch(e){toast(e.message)}}
async function adminBroadcastSend(){const m=$('adminBroadcast')?.value.trim();if(!m)return;try{await apiFetch('/api/admin/broadcast',{method:'POST',body:JSON.stringify({message:m})});$('adminBroadcast').value='';toast('Đã gửi toàn hệ thống');loadChat()}catch(e){toast(e.message)}}
async function renderAdminChat(){if(me?.role!=='admin')return;try{const list=(await apiFetch('/api/admin/chat')).messages;const el=$('adminChat');el.innerHTML=list.map(m=>`<div class="chatMsg"><b>${esc(m.username)}</b>: ${esc(m.message)}</div>`).join('')}catch(e){toast(e.message)}}
async function renderServerState(){try{const s=await apiFetch('/api/state');const el=$('apiStatus');if(el)el.textContent=`Node API: OK • Server: ${s.status}`}catch(e){if($('apiStatus'))$('apiStatus').textContent='Node API: lỗi'}}
async function setServerStatus(status){try{await apiFetch('/api/admin/state',{method:'POST',body:JSON.stringify({status})});toast('Đã đổi trạng thái server');renderServerState()}catch(e){toast(e.message)}}
async function loadServerBanner(){try{const s=await apiFetch('/api/state'),b=$('serverStatusBanner');if(!b)return;b.hidden=s.status==='normal';if(!b.hidden)b.textContent=s.display||'Server đang được bảo trì'}catch{}}
function adminSection(name){['Posts','Keys','Broadcast','Chat','Users','Server'].forEach(x=>$('adminSection'+x)?.classList.add('hidden'));const map={posts:'Posts',keys:'Keys',broadcast:'Broadcast',chat:'Chat',users:'Users',server:'Server'};if(map[name])$('adminSection'+map[name])?.classList.remove('hidden');else Object.values(map).forEach(x=>$('adminSection'+x)?.classList.remove('hidden'))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');if(id==='chat')loadChat();if(id==='admin')loadAdmin();if(id==='members')loadPublicUsers();if(id==='auth')renderProfile();if(id==='games')loadDinoLeaderboard()}
async function refreshAll(){syncAuthNav();renderProfile();loadPublicUsers();await refreshStats();await renderPosts();await loadServerBanner();if($('chat')?.classList.contains('active'))await loadChat();if($('admin')?.classList.contains('active'))await loadAdmin()}
function startPolling(){clearInterval(poll);poll=setInterval(async()=>{await loadPublicUsers();await refreshStats();await renderPosts();await loadServerBanner();if($('chat')?.classList.contains('active'))loadChat();if($('admin')?.classList.contains('active')){renderUsers();renderAdminChat()}},5000)}
function bootBanner(){const b=document.createElement('div');b.id='serverStatusBanner';b.hidden=true;b.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9999;padding:14px;text-align:center;font-weight:700;background:#222;color:#fff';document.body.appendChild(b)}
window.show=show;window.register=register;window.login=login;window.logout=logout;window.claimKey=claimKey;window.saveAvatar=saveAvatar;window.removeAvatar=removeAvatar;window.changePassword=changePassword;window.sendChat=sendChat;window.sendChatImage=sendChatImage;window.openPublicProfile=openPublicProfile;window.loadPublicUsers=loadPublicUsers;window.closeProfile=closeProfile;window.setUserRole=setUserRole;window.banIpForUser=banIpForUser;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.addKey=addKey;window.toggleKey=toggleKey;window.banUser=banUser;window.adminBroadcastSend=adminBroadcastSend;window.setServerStatus=setServerStatus;window.adminSection=adminSection;window.publishPost=publishPost;window.togglePost=togglePost;window.openPostLink=openPostLink;
bootBanner();if($('keyDate'))$('keyDate').value=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});init();

// Dino leaderboard mini-game
let dinoRAF=0,dinoRunning=false,dinoScore=0,dinoBest=Number(localStorage.getItem('ug_dino_best')||0),dinoLast=0,dinoSpeed=430,dinoSpawn=0,dinoObstacles=[],dinoY=0,dinoV=0,dinoGround=225;
function dinoCanvas(){return $('dinoCanvas')}
function dinoJump(){if(!dinoRunning)return; if(dinoY>=dinoGround-2){dinoV=-760}}
function startDinoGame(){const c=dinoCanvas();if(!c)return;cancelAnimationFrame(dinoRAF);dinoRunning=true;dinoScore=0;dinoSpeed=430;dinoSpawn=0;dinoObstacles=[];dinoY=dinoGround;dinoV=0;dinoLast=performance.now();$('dinoScore').textContent='0';$('dinoStatus').textContent='Đang chạy… nhảy qua xương rồng!';dinoRAF=requestAnimationFrame(dinoLoop)}
function endDinoGame(){dinoRunning=false;cancelAnimationFrame(dinoRAF);if(dinoScore>dinoBest){dinoBest=dinoScore;localStorage.setItem('ug_dino_best',String(dinoBest));$('dinoBest').textContent=dinoBest}$('dinoStatus').textContent=`💥 Game Over — ${dinoScore} điểm. ${me?'Đang lưu TOP server…':'Đăng nhập để ghi điểm TOP server.'}`;if(me)submitDinoScore(dinoScore);loadDinoLeaderboard()}
async function submitDinoScore(score){try{await apiFetch('/api/game/dino/score',{method:'POST',body:JSON.stringify({score})})}catch(e){toast(e.message)}}
async function loadDinoLeaderboard(){const el=$('dinoLeaderboard');if(!el)return;try{const rows=(await apiFetch('/api/game/dino/leaderboard')).scores;if(!rows.length){el.innerHTML='<p class="muted">Chưa có điểm. Hãy là người đầu tiên!</p>';return}el.innerHTML=rows.slice(0,10).map((r,i)=>`<div class="leaderRow ${i===0?'topOne':''}"><span class="rank">${i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1}</span><span class="leaderName">${esc(r.username)}</span><b>${Number(r.score).toLocaleString('vi-VN')}</b></div>`).join('')}catch(e){el.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
function dinoLoop(now){if(!dinoRunning)return;const c=dinoCanvas(),ctx=c.getContext('2d');const dt=Math.min(.032,(now-dinoLast)/1000);dinoLast=now;dinoSpeed=Math.min(760,dinoSpeed+dt*5);dinoV+=1900*dt;dinoY+=dinoV*dt;if(dinoY>dinoGround){dinoY=dinoGround;dinoV=0}dinoSpawn-=dt;if(dinoSpawn<=0){const h=34+Math.random()*42,w=18+Math.random()*18;dinoObstacles.push({x:c.width+30,w,h,passed:false});dinoSpawn=.8+Math.random()*.65-(dinoSpeed-430)/2200}
for(const o of dinoObstacles)o.x-=dinoSpeed*dt;dinoObstacles=dinoObstacles.filter(o=>o.x>-60);for(const o of dinoObstacles){if(!o.passed&&o.x+o.w<92){o.passed=true;dinoScore++;$('dinoScore').textContent=dinoScore}if(74<o.x+o.w&&106>o.x&&dinoY-44<dinoGround&&dinoY> dinoGround-o.h-4){return endDinoGame()}}
ctx.clearRect(0,0,c.width,c.height);const g=ctx.createLinearGradient(0,0,0,c.height);g.addColorStop(0,'#0b0920');g.addColorStop(1,'#101426');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#5e49ff';ctx.globalAlpha=.16;for(let x=0;x<c.width;x+=90)ctx.fillRect(x,40+(x%130),2,2);ctx.globalAlpha=1;ctx.fillStyle='#7c63ff';ctx.fillRect(0,dinoGround+2,c.width,3);ctx.fillStyle='#8b7cff';ctx.fillRect(78,dinoY-42,30,42);ctx.fillStyle='#b7adff';ctx.fillRect(101,dinoY-37,14,6);ctx.fillRect(100,dinoY-9,9,9);ctx.fillStyle='#45e6b0';for(const o of dinoObstacles){ctx.fillRect(o.x,dinoGround-o.h,o.w,o.h);ctx.fillRect(o.x-7,dinoGround-o.h+12,7,7);ctx.fillRect(o.x+o.w,dinoGround-o.h+24,7,7)}ctx.font='700 18px system-ui';ctx.fillStyle='#fff';ctx.fillText('SPACE / ↑ / TAP',18,30);dinoRAF=requestAnimationFrame(dinoLoop)}
function bindDinoInput(){const c=dinoCanvas();if(!c)return;['pointerdown'].forEach(ev=>c.addEventListener(ev,e=>{e.preventDefault();if(!dinoRunning)startDinoGame();else dinoJump()},{passive:false}));window.addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();if($('games')?.classList.contains('active')){if(!dinoRunning)startDinoGame();else dinoJump()}}})}
$('dinoBest')&&($('dinoBest').textContent=dinoBest);bindDinoInput();loadDinoLeaderboard();
